### ISSUE TITLE
Incorrect list informations from .get_keyword_from_articles()

### ISSUE THREAD

**Issue by yulian** [HQHAN/SecurePython#2]
Unnecessary informations are added after call .get_keyword_from_articles()
For examples) Output is that [u'Virtually', u'every', u'aspect', u'of' ...], this should be ['Virtually', 'every', 'aspect', 'of', ...]

**Comment by HQHAN** [comment]
@yulian ok. let me investigate on this and update here.

**Comment by HQHAN** [comment]
@yulian This is python's behaviour to show 'u' prefix to represent the string is encoded with unicode.
As i've shown, you can take the value without 'u' prefix when iterating over string list.

**Comment by yulian** [comment]
@HQHAN I got it.
